In [2]:
print(1)
print(2)

1
2


In [4]:
df=pandas.read_csv("D:\\SEM V Notes\\supermarkets\\supermarkets.csv")
df

NameError: name 'pandas' is not defined

In [6]:
import pandas
df=pandas.read_csv("D:\\SEM V Notes\\supermarkets\\supermarkets.csv")
df


ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [1]:
df=pandas.read_json("D:\\SEM V Notes\\supermarkets\\supermarkets.json")
df

NameError: name 'pandas' is not defined

In [3]:
import os
os.listdir()

['.ipynb_checkpoints',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Testing.ipynb']

In [4]:
import pandas
f1=pandas.read_csv("supermarkets.csv");
f1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [5]:
f1[0][State]

KeyError: 0

In [6]:
f1[0][0]

KeyError: 0

In [7]:
df = pandas.read_excel("supermarkets.xlsx",sheet_name=0)
df

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [9]:
df1=pandas.read_csv("supermarkets-semi-colons.txt",sep=";")
df1

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [11]:
df2=pandas.read_csv("supermarkets-commas.txt",header=None)
df2

0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [12]:
df2.columns=["id","address","state","zip","country","name","emp"]
df2

id          address          state               zip country         name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   emp  
0    8  
1   15  
2   25  
3   10  
4   12  
5   20

In [13]:
df3 = df2.set_index("id")
df3

address          state               zip country         name  emp
id                                                                            
1      3666 21st St  San Francisco          CA 94114     USA      Madeira    8
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   15
3       332 Hill St  San Francisco  California 94114     USA  Super River   25
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   10
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   12
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   20

In [14]:
df3.loc["2":"3","state":"name"]

state               zip country         name
id                                                      
2   San Francisco          CA 94119     USA  Bready Shop
3   San Francisco  California 94114     USA  Super River

In [15]:
list(df3.loc[:,"name"])

[' Madeira',
 'Bready Shop',
 'Super River',
 "Ben's Shop",
 'Sanchez',
 'Richvalley']

In [17]:
df3.iloc[1:3,1:3]

state               zip
id                                 
2   San Francisco          CA 94119
3   San Francisco  California 94114

In [25]:
df3.drop(df3.index[1:3])

address          state         zip country        name  emp
id                                                                     
1      3666 21st St  San Francisco    CA 94114     USA     Madeira    8
4      3995 23rd St  San Francisco    CA 94114     USA  Ben's Shop   10
5   1056 Sanchez St  San Francisco  California     USA     Sanchez   12
6   551 Alvarado St  San Francisco    CA 94114     USA  Richvalley   20

In [26]:
import geopy
dir(geopy)

['AlgoliaPlaces',
 'ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'Geocodio',
 'Geolake',
 'GoogleV3',
 'Here',
 'HereV7',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'What3WordsV3',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [28]:
df2=pandas.read_csv("supermarkets.txt")
df2

ID          Address         City_x           State_x Country_x  \
0   1     3666 21st St  San Francisco          CA 94114       USA   
1   2   735 Dolores St  San Francisco          CA 94119       USA   
2   3      332 Hill St  San Francisco  California 94114       USA   
3   4     3995 23rd St  San Francisco          CA 94114       USA   
4   5  1056 Sanchez St  San Francisco        California       USA   
5   6  551 Alvarado St  San Francisco          CA 94114       USA   

        Name_x  Employees_x         City_y           State_y Country_y  \
0      Madeira            8  San Francisco          CA 94114       USA   
1  Bready Shop           15  San Francisco          CA 94119       USA   
2  Super River           25  San Francisco  California 94114       USA   
3   Ben's Shop           10  San Francisco          CA 94114       USA   
4      Sanchez           12  San Francisco        California       USA   
5   Richvalley           20  San Francisco          CA 94114       USA   

        Name_y  Employees_y          Continent  
0      Madeira            8  USA North America  
1  Bready Shop           15  USA North America  
2  Super River           25  USA North America  
3   Ben's Shop           10  USA North America  
4      Sanchez           12  USA North America  
5   Richvalley           20  USA North America

In [29]:
from geopy.geocoders import ArcGIS


In [30]:
nom=ArcGIS()

In [31]:
nom.geocode("3995 23rd St,San Francisco,CA 94114")

Location(3995 23rd St, San Francisco, California, 94114, (37.75292099814533, -122.43170295955227, 0.0))

In [33]:
df = pandas.read_csv("supermarkets.csv")
df["Address"]=df["Address"]+", "+df["City"]+", "+df["State"]+", "+df["Country"]
df


ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [34]:
df["Coordinates"]=df["Address"].apply(nom.geocode)

In [35]:
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [36]:
df.Coordinates[0]

Location(3666 21st St, San Francisco, California, 94114, (37.756632001957215, -122.42941101194798, 0.0))

In [38]:
df["Latitude"]=df["Coordinates"].apply(lambda x: x.latitude if x!=None else None)
df["Longitude"]=df["Coordinates"].apply(lambda x: x.longitude if x!=None else None)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

In [41]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [42]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [43]:
import cv2

In [45]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [46]:
cv2.imwrite("newSmallgray.png",im_g)

True